### ISSUE TITLE
Simplifying the Add Item page - Advanced Settings

### ISSUE THREAD

**Issue by zomer-g** [OriHoch/data4dappl#107]
Advanced Settings is broken link

![image](https://user-images.githubusercontent.com/30901226/62695717-89aa5d80-b9df-11e9-9161-a7be53472206.png)

**Comment by OriHoch** [comment]
@zomer-g which browser and browser version are you using?

**Comment by OriHoch** [comment]
@zomer-g nevermind, found the problem (happens in Firefox)

**Comment by OriHoch** [comment]
deployed
