### ISSUE TITLE
upload via mail

### ISSUE THREAD

**Issue by zomer-g** [OriHoch/data4dappl#109]
In the last few days, it stopped to upload via mail.

**Comment by OriHoch** [comment]
fixed + added a Jenkins job which checks status every day and restarts in case of problems (runs on k972il's jenkins server)

**Comment by zomer-g** [comment]
The system stopped uploading files from the email. They remain in the mailbox in unread mode, at least since 22q9q2019 day, when the last time it uploaded via mail was 18/9/2019

**Comment by OriHoch** [comment]
restarted

hopefully fixed the automatic restart job - https://nbviewer.jupyter.org/github/hasadna/hasadna-k8s/blob/master/Odata%20-%20debug%20production%20pipelines.ipynb

**Comment by zomer-g** [comment]
Stopped upload since yesterday

**Comment by OriHoch** [comment]
@zomer-g  there were some upgrades to hasadna cluster which caused this, fixed now

**Comment by OriHoch** [comment]
fixed..

**Comment by OriHoch** [comment]
the Jenkins server with the monitor job had problems.. moved this task to Kubernetes so we have less external dependencies.. hopefully fixed :unamused:
