### ISSUE TITLE
footer update

### ISSUE THREAD

**Issue by zomer-g** [OriHoch/data4dappl#110]
please add links to 
מדיניות פרטיות
https://www.odata.org.il/en_US/dataset/privacy-policy

and

הצהרת נגישות
https://www.odata.org.il/en_US/dataset/accessibility-statement

in the footer. 
Just Hebrew text, don't need to be translate because the docs are in Hebrew anyway.

**Comment by OriHoch** [comment]
done + deployed

FYI - it's pretty easy to make these kind of changes directly to the relevant HTML template in GitHub, in this case, the footer template - https://github.com/OriHoch/data4dappl/edit/master/ckan/ckanext-odata_org_il/ckanext/odata_org_il/templates/footer.html

Once you are done you can choose to either commit directly - which will cause it to deploy the change, or to open a pull request which I can review before deploying
