### ISSUE TITLE
add new tab of "ישויות" in group page

### ISSUE THREAD

**Issue by zomer-g** [OriHoch/data4dappl#113]
![image](https://user-images.githubusercontent.com/30901226/68997934-9d097680-08b4-11ea-9bb4-f70b8f9312a2.png)

in the new tab (the page url should look like this https://www.odata.org.il/group/<group url>):

add a list of the related group for each group (it's the same list of groups in the group page). 

each group should be  in separate line which represent relation between the group of the page and other group.

for each group in the list that has more groups with connection, we should add a expansion button with the number of objects related to this group. 

when pressing on the expansion button, all the connected groups to the specific group should appear under that (like the picture below).

![גרסה 4 שלב 2](https://user-images.githubusercontent.com/30901226/68997952-c4f8da00-08b4-11ea-89bc-7a7671a31e26.png)

put attention, that all the new group names, changed from expansion to reduction. 

In addition, each group should be clickable to the group page. 

More important than what it looks like, is that this table that represents relationships between entity pairs will be machine readable and a simple and clean API can be provided to display the context map (even if it will look less beautiful).

The context map should basically be such a table that clicking on the map on "+" will work just like clicking on a expansion button. It's means that the data behind each line will look like entity A, entity B (while A is the tiitle of the part of the table).

For me, after Nir will build the map, i want to embed it at the beginning of the tab, and the table underneath the map, will be updated in real time based on map clicks (this will also be good in terms of accessibility regulations and SEO)

**Comment by zomer-g** [comment]
each group in the list should be clickable to the group page entities, like the GROUPS, TAGS and others in the right menu now.

**Comment by OriHoch** [comment]
@zomer-g done - https://www.odata.org.il/group/entities?name=mof
