### ISSUE TITLE
earch engine

### ISSUE THREAD

**Issue by zomer-g** [OriHoch/data4dappl#114]
When you are in a group page (url: https://www.odata.org.il/group/<group url>), the search engine should look for groups (entities and not documents)

![image](https://user-images.githubusercontent.com/30901226/68532404-759b3280-0325-11ea-8dfa-fcc2a23ef00a.png)

**Comment by OriHoch** [comment]
when you are on the main groups page (https://www.odata.org.il/group) it searches for entities

when you are on a specific group page, under the documents tab (https://www.odata.org.il/group/hit) it searches in this group's documents

this is default ckan behavior which seems hard to modify

**Comment by zomer-g** [comment]
ok,
leave it, it's not so important
