### ISSUE TITLE
upload files

### ISSUE THREAD

**Issue by zomer-g** [OriHoch/data4dappl#123]
some of the files failed to upload. 
if you try to open/download the files, it get error.
tried to upload all this files twice. second time with drag and drop on 3 group of files. still have the same problem. 
some files work well and some are broken

https://www.odata.org.il/dataset/comp-inst

**Comment by OriHoch** [comment]
problem was due to a bug in file uploader UI with rename of dataset URL

rename back to original URL fixed the problem:
https://www.odata.org.il/dataset/2019-2
