### ISSUE TITLE
remove duplicate connection from entity table

### ISSUE THREAD

**Issue by zomer-g** [OriHoch/data4dappl#126]
after expanding the entity table, we should check that there are no duplicates connections 

![image](https://user-images.githubusercontent.com/30901226/71424271-b615fc00-2698-11ea-8d4a-335dad8a7b77.png)

**Comment by zomer-g** [comment]
it doesn't expand any

![image](https://user-images.githubusercontent.com/30901226/71425896-fe3e1a00-26aa-11ea-8ad8-40faa7b7ed65.png)

**Comment by OriHoch** [comment]
All the related entities to these entities are displayed on the table and related to the source group משרד האוצר - so they are all duplicated connections and according to this issue were removed.

**Comment by zomer-g** [comment]
You are right I was idiot. Sorry
