### ISSUE TITLE
Elad file upload via mail - fail

### ISSUE THREAD

**Issue by zomer-g** [OriHoch/data4dappl#136]
When Elad send a mail to ODATA, it create a new dataset with the right tittle. But, instead of adding the files it's just upload two pictures from his mail-sign. 
*It happen on his mail but not on my mail (and i guess the bug reproduce only on his mail). So if I send from ODATA-mail to my private mail and than send it again to ODATA, it upload correct. 

![image](https://user-images.githubusercontent.com/30901226/82342482-5b3fc100-99fa-11ea-9ca5-046b3d87555a.png)

**Comment by OriHoch** [comment]
fixed + deployed
