### ISSUE TITLE
גיבוי ופרסום קוד אתר

### ISSUE THREAD

**Issue by zomer-g** [OriHoch/data4dappl#16]
בכל מקרה, היות וזה פרויקט קוד פתוח, חשוב לי מאד שהקוד יהיה נגיש ופומבי. לא מבין ברמת הפיתוח אם מפרסמים את זה כיחידות נפרדות שעברו שינוי או את כל הקוד קומפלט, אבל חשוב לוודא שזה פומבי. 

דבר שני, חשוב שיהיה לאתר גיבוי, גם ברמת התוכן שמאוחסן על השרת וגם ברמת הקוד.

**Comment by OriHoch** [comment]
currently all the code is public in this repository

you can also download every release as a zip file from the releases page - https://github.com/OriHoch/data4dappl/releases

regarding data - yes, will take care of that

**Comment by OriHoch** [comment]
once we move to the new servers (donated from Hasadna) - we will use [Kubernetes]() for deployments - which will have much better support for backup and availability.

this will be handled in #28 

keeping this issue open - to ensure that we took care of backup and all that stuff on the new servers
