### ISSUE TITLE
Footer and API

### ISSUE THREAD

**Issue by zomer-g** [OriHoch/data4dappl#18]
![image](https://user-images.githubusercontent.com/30901226/29425731-ffa88196-838c-11e7-82ec-b8ac15707072.png)

1. האם יש באמת API עובד, והאם זה בכלל רלוונטי לסוג האתר בפועל. אם אין וזה גם לא ממש שימושי, אז רק צריך להסיר את הכיתוב בעניין זה. 

2. לסדר מילולית את הביטוי "ממשק המכונה (API) של תביאתה"

3. נראה לי שבפוטר כדאי להוסיף את הקישור לקוד, אלא אם מקובל להכניס במקום אחר. 

4. להוסיף קישור לעמוד פייסבוק
https://www.facebook.com/%D7%9E%D7%99%D7%93%D7%A2-%D7%9C%D7%A2%D7%9D-300350757102935/notifications/

**Comment by OriHoch** [comment]
need to also add credit and link to [Hasadna](http://www.hasadna.org.il/) - because they pay for our servers

**Comment by zomer-g** [comment]
אין בעיה. אתה רוצה להוסיף את זה כטקסט קליקבילי או שאתה רוצה שאסגור את זה במשהו גרפי. אם גרפי, רק תגיד מה בדיוק צריך.

**Comment by OriHoch** [comment]
a simple credit for Hasadna was added (it's deployed at https://www.odata.org.il/)

still need to work on this issue according to requirements here

**Comment by OriHoch** [comment]
related: #45
