### ISSUE TITLE
Information Requests Wizard

### ISSUE THREAD

**Issue by zomer-g** [OriHoch/data4dappl#20]
<div dir=rtl>
באתר חופש המידע יש אשף הגשת בקשות. זה מערכת של 3 שאילתות שבהס"כ מייצרים URL עם 3 הפרמטרים האלה. 
https://foi.gov.il/he/inforequest

אז עשיתי קצת הנדסה לאחור לפרמטרים שלו ודימיתי את המבנה הזה כנוסחא באקסל. מבחינת DB, אז אני שואב אותו אוטומטית מהאתר, ככה שהוא כל הזמן מעודכן. 
https://foi.gov.il/GetallofficetolistXMLpublished

כרגע יש פער טכני אחד שהמערכת לא יודעת לזהות לאיזה רשויות יש תשלום מקוון ולכן מאפשרת את זה לכולם אבל לגבי אלה שאין, זה יגרום לקבלת שגיאה בשלב הסליקה מול חברת האשראי. אבל יש לי בקשה שצריכה להענות בקרוב לקבל את רשימת הרשויות עם תשלום מקוון ואז אני מקווה לעדכן את הנוסחא ככה שתגביל אותך מלשלוח לרשות שאין לה תשלום מקוון טופס עם תשלום מקוון. 

מה שכן, תהיתי כמה פשוט זה להטמיע את הנוסחא הזאת לתוך האתר. זה בסך הכל מנגנון חיפוש של שם הרשות מתוך הDB (יושב בXML), בחירה של סוג מידע וסוג תשלום. הנוסחא ממש בסיסית. 

[אשף בקשות מידע.xlsx](https://github.com/OriHoch/data4dappl/files/1237050/default.xlsx)

מבחינת יתרונות של זה על האשף הקיים, זה שקודם כל ממשל זמין לא מבינים איך לחבר את האשף לטופס בצורה אוטומטית, אז באשף יש רק 675 רשויות ובטופס 1830 רשויות. דבר שני, באשף יש מלא באגים (גם בטופס אבל עליהם אין לי איך לדלג). דבר שלישי, זה יכול להיות ממשק הרבה יותר מהיר ופשוט בלי כל הגרפיקה המנופחת הזאת. רק 3 פרמטרים, מזין בשנייה ולחיצה, ואת בטופס המקוון. 

בנוסף, יש אפשרות לטעון את הטופס בXML ובמצב כזה אני יכול למלא את כל השדות שאני רוצה. אני השבוע אנסה לעשות קצת הנסדה לאחור ולהבין את הלוגיקה בXML. אם אני אבין איך לעשות מניפולציות על התוכן כדי להתאים ולשלוט בטופס המקוון, אז אעלה את הנוסחאות האלה ,אבל אני פחות אופטימי מהמקרה הזה. כאן זה סתם ברמת הURL אז מאד קל לי לחקות את זה. 
</div>

**Comment by OriHoch** [comment]
It's very hard to understand what you need

some background and high-level details about what is your end-goal will be useful

**Comment by zomer-g** [comment]
האמת שזה לגמרי סיפור זניח לחלוטין ומיותר, אז נראה לי עדיף פשוט לסגור את זה וזהו
