### ISSUE TITLE
dataset pages should be displayed properly on mobile - without horizontal scroll

### ISSUE THREAD

**Issue by zomer-g** [OriHoch/data4dappl#21]
![screenshot_20170821-085605](https://user-images.githubusercontent.com/30901226/29506105-a7766b3c-8652-11e7-93e2-514399ef9318.png)

באתר בפלאפון במסכים של הפריטים באתר (לינקים לדוגמא בהמשך) העמוד שמוצג גדול משמעותית (פי כמה עשרות) מהדף עצמו. כלומר כשאתה עושה זום-אווט, אתה מקבל מסך ענקי וריק. 

בדקתי את זה בעמוד רשויות ובתוך רשויות לדוגמא, בעמוד ארגונים ובתוך ארגונים לדוגמא, בעמוד אודות ובעמודים של המאגרים עצמם (בתוך הפריטים) ואין את התקלה הזאת בעמודים אחרים שבדקתי. 

זה מתרחש בכל העמודים בהיררכיה הזאת
https://www.odata.org.il/dataset/israelschools
https://www.odata.org.il/dataset/levin-c
https://www.odata.org.il/dataset/cohene-c
https://www.odata.org.il/dataset/information-systems-division

**Comment by OriHoch** [comment]
fixed, merged and deployed
https://www.odata.org.il/dataset/israelschools
https://www.odata.org.il/dataset/levin-c
https://www.odata.org.il/dataset/cohene-c
https://www.odata.org.il/dataset/information-systems-division
