### ISSUE TITLE
should change the logo in the header

### ISSUE THREAD

**Issue by zomer-g** [OriHoch/data4dappl#22]
לא בדיוק ברור לי מה נעשה בסוף עם הלוגו, אבל לבנתיים במקום CKAN, שיהיה משהו שקשור למידע לעם, הכנתי איזה PNG עם טקסט בסגנון הזה. 

הוא יושב על אותם פיקסלים של הלוגו הקיים, אז להבנתי זה ממש רק להחליף ראש בראש בלי לגעת בדברים מעבר
זה הכינוי של הקובץ כרגע
ckan-logo.png

![default](https://user-images.githubusercontent.com/30901226/29743454-19b91dd8-8a9b-11e7-8e1d-763564ff0478.png)

הלוגו למטה של CKAN לדעתי עדיף להשאיר, כדי שמי שמגיע לאתר ידע מה המקור וכו'.

**Comment by OriHoch** [comment]
fixed, merged and deployed
https://www.odata.org.il/
