### ISSUE TITLE
Block Google from indexing the site in other languages

### ISSUE THREAD

**Issue by zomer-g** [OriHoch/data4dappl#24]
![image](https://user-images.githubusercontent.com/30901226/29770599-80984a3e-8bf8-11e7-9d71-457d016f1e72.png)

**Comment by zomer-g** [comment]
משיטוט בדש בורד, אם הבנתי נכון, אז צריך להחליף את הקובץ טקסט של ROBOTS בקובץ הבא, ואז לחזור לדשבורד הזה וזה אמור להתחיל לחסום את גוגל מלאנדקס את השפות הזרות. עשיתי את זה ידנית אז יכול להיות שבטעות פיספסתי שפה אחת, אבל בסך הכל אני די בטוח שזה סוגר אתכל השפות.

זה הקובץ טקסט
https://www.odata.org.il/robots.txt





User-agent: *
Disallow: /dataset/rate/
Disallow: /revision/
Disallow: /dataset/*/history
Disallow: /api/
Disallow: /en
Disallow: /pt_BR
Disallow: /ja
Disallow: /it
Disallow: /cs_CZ
Disallow: /ca
Disallow: /es
Disallow: /fr
Disallow: /el
Disallow: /sv
Disallow: /sr
Disallow: /no
Disallow: /sk
Disallow: /fi
Disallow: /ru
Disallow: /de
Disallow: /pl
Disallow: /nl
Disallow: /bg
Disallow: /ko_KR
Disallow: /hu
Disallow: /sl
Disallow: /lv
Disallow: /en_AU
Disallow: /tl
Disallow: /uk_UA
Disallow: /lt
Disallow: /sq
Disallow: /pt_PT
Disallow: /fa_IR
Disallow: /hr
Disallow: /zh_TW
Disallow: /es_AR
Disallow: /ro
Disallow: /tr
Disallow: /sr_Latn
Disallow: /is
Disallow: /id
Disallow: /zh_CN
Disallow: /mn_MN
Disallow: /da_DK
Disallow: /vi
Disallow: /ar
Disallow: /km
Disallow: /ne
Disallow: /th

User-Agent: *
Crawl-Delay: 10

**Comment by OriHoch** [comment]
thanks, merged and deployed
https://www.odata.org.il/robots.txt

**Comment by zomer-g** [comment]
סבבה, עדכנתי את זה בקונסולה הזאת ועשיתי לו טסטים ונראה שלגבי הקדימה זה סגר את הסיפור והבעיה תוקנה. 

לגבי אחורה, אני עכשיו מנסה לעשות לו הסרה של הURLים האלה, אעדכן בהמשך.


![image](https://user-images.githubusercontent.com/30901226/29863555-b21e04f0-8d78-11e7-8e4b-03c1411d6df2.png)

**Comment by zstadler** [comment]
The [google search results](https://www.google.com/search?q=%22%D7%A0%D7%99%D7%92%D7%95%D7%93+%D7%A2%D7%A0%D7%99%D7%99%D7%A0%D7%99%D7%9D+%D7%A8%D7%95%D7%99%D7%AA+%D7%94%D7%A8%D7%9E%D7%9F%22) still show results in Macedonian - `/mk/`

![image](https://user-images.githubusercontent.com/1304610/46904326-11702a00-ceeb-11e8-9a0d-286c8c6df8f2.png)
