### ISSUE TITLE
Dates should be shown in simple consistent format with field labels in hebrew

### ISSUE THREAD

**Issue by zomer-g** [OriHoch/data4dappl#25]
![image](https://user-images.githubusercontent.com/30901226/29791256-f823cf8c-8c44-11e7-8081-c5fac49f66dd.png)

<p dir=rtl>
אשמח אם תוכל לתקן שיהיה כתוב "עודכן לאחרונה" במקום Last Updated
בנוסף, מבנה התאריך צריך להיות DD/MM/YY, בלי שעה ובלי הבלאגן שם עם שם החודש. 
</p><p dir=rtl>
תודה רבה
</p>

**Comment by OriHoch** [comment]
related: #51 #52

**Comment by OriHoch** [comment]
fixed in 2.8.1
