### ISSUE TITLE
Open permissions to classify authorities

### ISSUE THREAD

**Issue by zomer-g** [OriHoch/data4dappl#27]
<p dir=rtl>
כרגע רק מי שיצר רשות יכול לסווג רשות. בפועל מכיוון שאני פתחתי את כל הרשויות, רק אני יכול לסווג את התשובות לפי רשויות. כלומר הארגונים מעלים את התשובה ואני כל פעם צריך לסווג את הרשות. אני חושב שכדאי לתקן את זה כך שההרשאה תהיה שכל ארגון יכול לסווג כל רשות לגבי התשובות שיש לארגון הרשאה לערוך. 
</p><p dir=rtl>
צריך לשים לב שלא מאפשרים לכל משתמש לסווג רשויות, כי בסוף אנחנו כרגע לא מגבילים פתיחת משתמשים ובעצם כל אחד שירצה להטריל את האתר יוכל לפתוח משתמש להיכנס ולסווג רשויות. החסם כרגע הוא שמשתמש חדש לא יכול לפתוח ארגון וממילא לא יוכל להעלות תוכן. אז גם סיווג ההרשאות צריך להיות מותנה בקבלת הרשאה לארגון ספציפי. 
</p>

![image](https://user-images.githubusercontent.com/30901226/30243131-dfa489cc-95ab-11e7-813a-53acc9d38828.png)

**Comment by OriHoch** [comment]
## reproduction
* log in as organization user
* edit dataset groups - https://www.odata.org.il/dataset/groups/shufersal

### expected
* option to assign groups
* all organization users should have access to all groups
![image](https://user-images.githubusercontent.com/1198854/45202335-53210b80-b281-11e8-85f9-e690e2cdc16e.png)

### actual
* no option to assign groups
