### ISSUE TITLE
 Add a social media sharing button on the main page and item pages

### ISSUE THREAD

**Issue by zomer-g** [OriHoch/data4dappl#30]
**Welcome [Hacktorberfest 2017](https://hacktoberfest.digitalocean.com/) participants - please read this [introduction](https://github.com/OriHoch/data4dappl/wiki/Hacktoberfest-2017-participants-introduction) written specifically for Hacktoberfest participants to help you get oriented with the project and get a PR ready and deployed ASAP. Feel free to ask any questions or clarifications regarding this issue in the issue comments**

### reproduction

* goto homepage: https://www.odata.org.il/en/
* goto dataset page: https://www.odata.org.il/en/dataset/kamings

##### expected

* should have social sharing buttons (Facebook / Twitter etc..)
* should ensure page metadata is read correctly (e.g. og: attribute)

##### actual

* no sharing

### implementation notes

there is a ckan extension which is supposed to do that - https://github.com/okfn/ckanext-social

**Comment by OriHoch** [comment]
can use https://github.com/okfn/ckanext-social

**Comment by OriHoch** [comment]
related: #45
