### ISSUE TITLE
Capital letters in url

### ISSUE THREAD

**Issue by zomer-g** [OriHoch/data4dappl#32]
כשבוחרים URL לפריט מידע חדש, בעבר היה ניתן לכתוב גם אותיות גדולות והוא היה מתעלם. כעת כתיבה של אותיות גדולות מייצרת תקלה ולא מאפשר ליצור את הפריט אלא לאחר החלפת האותיות הגדולות באותיות קטנות בלבד.

**Comment by OriHoch** [comment]
@zomer-g I didn't fully understand but try again, I fixed something

if still doesn't work, please provide specific example

**Comment by zomer-g** [comment]
אכן תוקן, עובד טוב. תודה רבה
