### ISSUE TITLE
footer: add links to facebook, RSS and other social sites / links

### ISSUE THREAD

**Issue by OriHoch** [OriHoch/data4dappl#45]
* show icons which links to the relevant pages
* facebook page: https://www.facebook.com/%D7%9E%D7%99%D7%93%D7%A2-%D7%9C%D7%A2%D7%9D-300350757102935/
* RSS: https://www.odata.org.il/feeds/dataset.atom

Other links TBD

**Comment by zomer-g** [comment]
Following a version update, the RSS structure has changed and now generates error messages


https://www.odata.org.il/feeds/dataset.atom

**Comment by OriHoch** [comment]
@zomer-g deleted last comment, will be fixed in #62

**Comment by OriHoch** [comment]
deployed
@zomer-g if you have other links to add, please open a new issue
