### ISSUE TITLE
organization / group page: add RSS icon

### ISSUE THREAD

**Issue by OriHoch** [OriHoch/data4dappl#47]
RSS link example: https://www.odata.org.il/feeds/organization/hatzlacha.atom

![image](https://user-images.githubusercontent.com/1198854/44046448-25ed05fc-9f34-11e8-9a78-f28e8d1fdcc4.png)

**Comment by zomer-g** [comment]
Following a version update, the RSS structure has changed and now generates error messages


https://www.odata.org.il/feeds/dataset.atom

**Comment by OriHoch** [comment]
@zomer-g deleted last comment, will be fixed in #62

**Comment by OriHoch** [comment]
deployed
