### ISSUE TITLE
theme: revert color changes - back to ckan theme

### ISSUE THREAD

**Issue by OriHoch** [OriHoch/data4dappl#49]
need to get new odata logo with transparent background

relevant commit: https://github.com/OriHoch/data4dappl/commit/0850d6038a5b4caec782dfee4117793cd5ea519f

**Comment by zomer-g** [comment]
![meidalaam](https://user-images.githubusercontent.com/30901226/44151609-c02879da-a0ab-11e8-836c-038fa219e0c3.png)


מצורף לוגו בשקוף כדי שיהיה סבבה עם החלפת הרקע

**Comment by OriHoch** [comment]
additional comments regarding color change (after upgrading to ckan 2.8)

<p dir=rtl>
יש לי רק עניין אחד בכל הנוגע לעיצוב וזה קשור לתקנות נגישות. יש הגדרה של קונטרסט בין טקסט לרקע. אז אם מחליפים צבעים של אלמנטים חשוב שנוודא בסוף התהליך שאנחנו שומרים על קונטרסט מינימלי. כי התוכנית שלי שכל האתר יהיה בקונטרסט הנכון במצב הטבעי ובלי הכפתורים הדבילים האלה שמחליפים צבעים. בכלל, אני מנסה להבין איך אפשר להטמיע את כל הדרישות של נגישות במצב הרגיל של האתר ובלי הכפתור וכל הפיצ'רים המוזרים והמעצבנים האלה שיש במלא אתרים.
</p>

<p dir=rtl>
נגיד מקרים כאלה, יכול להיות שנצטרך לשים צבע כהה יותר כדי לעמוד בדרישת ניגודיות בין טקסט לרקע.
</p>

![image](https://user-images.githubusercontent.com/1198854/44715680-0d19ba00-aac1-11e8-8c7f-2fe0316a8bde.png)

<p dir=rtl>
הצבע שכרגע יש עם הכחול החדש, הוא תופס מבחינת כותרות אבל לא מתאים מבחינת תוכן.
</p>

![image](https://user-images.githubusercontent.com/1198854/44715716-1efb5d00-aac1-11e8-8f1f-c8f6c017356c.png)

<p dir=rtl>
בצבע הקודם, הניגוד היה מספיק גם לטקסט ולא רק לכותרת.
</p>

![image](https://user-images.githubusercontent.com/1198854/44715734-2ae71f00-aac1-11e8-8503-ae3d5bd82c9e.png)

<p dir=rtl>
הכחול החדש עם טקסט לבן לחלוטין עובר בקושי. אבל לדעתי כדאי להכהות את הרקע כמו שהיה בעבר
</p>

![image](https://user-images.githubusercontent.com/1198854/44715753-35a1b400-aac1-11e8-8813-300be8064185.png)

<p dir=rtl>
גם זה בעייתי, אלא אם תגיד שאתה מעדיף לעשות כפתור שימיר את כל האתר ל-2 צבעים במקום לוודא שהכל עומד בדרישת ניגודיות.
</p>

![image](https://user-images.githubusercontent.com/1198854/44715781-47835700-aac1-11e8-80f7-6a7dc9b3be28.png)

**Comment by OriHoch** [comment]
moved comments regarding color contrast to #63
