### ISSUE TITLE
translate to arabic

### ISSUE THREAD

**Issue by OriHoch** [OriHoch/data4dappl#53]
need to get excel of word translations aggregated manually from the site - https://www.odata.org.il/ar/

**Comment by zomer-g** [comment]
אני אשמח אם תוכל לייצא את המילים שיש בלוג הזה, כי יהיה קשה לדעת שאני אוסף את כולם באופן ידני. 
(דורש כניסה עם יוזר)
https://www.odata.org.il/dashboard

**Comment by OriHoch** [comment]
@zomer-g Arabic translations can be done in Transifex - 
Core CKAN strings - https://www.transifex.com/the-public-knowledge-workshop/hasadna-ckan/dashboard/
Odata specific strings - https://www.transifex.com/the-public-knowledge-workshop/odata-org-il/dashboard/

**Comment by zomer-g** [comment]
the translation in transfix - done
