### ISSUE TITLE
group page - add option to send foi requests (via mail or external form)

### ISSUE THREAD

**Issue by OriHoch** [OriHoch/data4dappl#59]
## reproduction
* go to group page: https://www.odata.org.il/he/group/mineduc

#### expected
* if the group has custom attribute `OfficeNameCode` - 
  * show option to send foi requests to the group via mail or link to external form
  * use the data from [xml](https://foi.gov.il/GetallofficetolistXMLpublished) or [json](https://foi.gov.il/he/free_info/ajax_offices) to get the details for the current group based on matching `OfficeNameCode`
  * retrieve the following data:
    * `Email`
    * `MMDOfficesTypes`
  * get the `kind` based on `MMDOfficesTypes` value based on static mapping (if json is not viable)
  * note the the json option is based on api which may change, xml is linked to from foi website
* send email link to `Email`
* online forum link: use a template link URL (TBD) replacing the values from `kind` and `OfficeNameCode`
![image](https://user-images.githubusercontent.com/1198854/44050778-b39490ee-9f40-11e8-894b-50ea0e0d9e69.png)

#### actual
no option to send foi requests

**Comment by zomer-g** [comment]
[KIND TABLE.xlsx](https://github.com/OriHoch/data4dappl/files/2284338/KIND.TABLE.xlsx)

**Comment by zomer-g** [comment]
need to fix the authority import so the request button will appear in more groups page
