### ISSUE TITLE
RSS feed error after upgrade to ckan 2.8.1

### ISSUE THREAD

**Issue by OriHoch** [OriHoch/data4dappl#62]
Following a version update, the RSS structure has changed and now generates error messages

https://www.odata.org.il/feeds/dataset.atom

**Comment by OriHoch** [comment]
@zomer-g fixed

**Comment by zomer-g** [comment]
נראה לי זה חזר על עצמו. במקום קישור לפריט הוא פשוט שולח אותך ל

https://www.odata.org.il/api/3/action/package_read?id=9abbff53-ae4d-4e00-ab70-fbb7ca4889a7
