### ISSUE TITLE
color contrast adjustments

### ISSUE THREAD

**Issue by OriHoch** [OriHoch/data4dappl#63]
<div dir=rtl>
יש לי רק עניין אחד בכל הנוגע לעיצוב וזה קשור לתקנות נגישות. יש הגדרה של קונטרסט בין טקסט לרקע. אז אם מחליפים צבעים של אלמנטים חשוב שנוודא בסוף התהליך שאנחנו שומרים על קונטרסט מינימלי. כי התוכנית שלי שכל האתר יהיה בקונטרסט הנכון במצב הטבעי ובלי הכפתורים הדבילים האלה שמחליפים צבעים. בכלל, אני מנסה להבין איך אפשר להטמיע את כל הדרישות של נגישות במצב הרגיל של האתר ובלי הכפתור וכל הפיצ'רים המוזרים והמעצבנים האלה שיש במלא אתרים.
<br/><br/>
נגיד מקרים כאלה, יכול להיות שנצטרך לשים צבע כהה יותר כדי לעמוד בדרישת ניגודיות בין טקסט לרקע.
<br/><br/>

![image](https://user-images.githubusercontent.com/1198854/44955159-b55fc200-aeb7-11e8-9d33-d84a6d32d76a.png)

<br/><br/>
הצבע שכרגע יש עם הכחול החדש, הוא תופס מבחינת כותרות אבל לא מתאים מבחינת תוכן.
<br/><br/>

![image](https://user-images.githubusercontent.com/1198854/44955161-bd1f6680-aeb7-11e8-9d0d-5a3e943de47f.png)

<br/><br/>
בצבע הקודם, הניגוד היה מספיק גם לטקסט ולא רק לכותרת.
<br/><br/>

![image](https://user-images.githubusercontent.com/1198854/44955165-c6a8ce80-aeb7-11e8-99ee-9eccd9dddc9a.png)

<br/><br/>
הכחול החדש עם טקסט לבן לחלוטין עובר בקושי. אבל לדעתי כדאי להכהות את הרקע כמו שהיה בעבר
<br/><br/>

![image](https://user-images.githubusercontent.com/1198854/44955168-ce687300-aeb7-11e8-965c-c4b00f501655.png)

<br/><br/>
גם זה בעייתי, אלא אם תגיד שאתה מעדיף לעשות כפתור שימיר את כל האתר ל-2 צבעים במקום לוודא שהכל עומד בדרישת ניגודיות.

![image](https://user-images.githubusercontent.com/1198854/44955170-d4f6ea80-aeb7-11e8-8ae2-8337286f3db3.png)

</div>

**Comment by OriHoch** [comment]
![image](https://user-images.githubusercontent.com/1198854/45202867-fc1c3600-b282-11e8-8fbd-18747ae1f643.png)

**Comment by OriHoch** [comment]
adjust contrast of format colors
![image](https://user-images.githubusercontent.com/1198854/45202980-51f0de00-b283-11e8-8825-387c1d068966.png)

**Comment by OriHoch** [comment]
![image](https://user-images.githubusercontent.com/1198854/45203163-e9563100-b283-11e8-91dc-1fb919a787a8.png)

**Comment by zomer-g** [comment]
באופן כללי צריך לשאוף שכל טקסט על רקע כהה יהיה בלבן מלא, וכל טקסט על רקע בהיר יהיה בשחור מלא.

**Comment by OriHoch** [comment]
fixed in #76 #75 #79
