### ISSUE TITLE
data from FOI requests should contain the request itself and not only the response

### ISSUE THREAD

**Issue by OriHoch** [OriHoch/data4dappl#7]
Elad:
<div dir=rtl>
אולי אנחנו רוצים להכניס בשדה או צירוף נפרד את הבקשה עצמה                        

לא רק את התשובות                        

ואולי תכתובת נלווית
</div>

**Comment by OriHoch** [comment]
Guy:
<div dir=rtl>
איפה שמצאתי בקשת מידע נקייה הכנסתי. זה פשוט לא מקוטלג טוב וסתם זרוק יחד עם התשובה, אבל זה בפנים. 
https://www.odata.org.il/dataset/bikoret-pnim
</div>

**Comment by OriHoch** [comment]
Elad:
<div dir=rtl>                       
אולי אפשר לנסות לאמבד את הטופס של הגשת הבקשות לאתר כך שעם הגשת בקשה ייפתח דף חדש לאותה בקשה שמכיל את הפדף של הבקשה                        

ושברירת המחדל של זה תהיה חסוי
</div>

**Comment by zomer-g** [comment]
לגבי אמבוד של טופס הגשת הבקשות ממליץ בחום לחכות. ממשל זמין כל הזמן עובדים על שינויים בדבר הזה וחבל שנעבוד ונתאים את עצמנו לטופס ולמחרת יחליפו טופס

**Comment by zomer-g** [comment]
מבחינתי אם למישהו חשוב שיהיו גם הבקשות, בטח עכשיו שיש העלאה של קבצים מרובים, שפשוט יעלו ביחד עם התשובות. לא רואה הצדקה לפתח משהו ייעודי
