### ISSUE TITLE
import all foi gov il entities (רשויות) into odata רשויות

### ISSUE THREAD

**Issue by OriHoch** [OriHoch/data4dappl#71]
before import - delete existing רשויות

**Comment by zomer-g** [comment]
ביבוא הנתונים, כדאי לשתול בהצגה פומבית כבר בשלב הראשוני את השדה 
"
GovXContentSection
"

שהוא למעשה תיאור התפקיד של הרשות. מדובר על שדה שנכתב מכורח החוק ולא משהו סתמי, ועדיף מראש שיוצג כבר במידע לעם כDescription של הארגון.

![image](https://user-images.githubusercontent.com/30901226/45778929-82148580-bc62-11e8-8a4b-9f0b330e4dff.png)
 

בנוסף, כל השדות של יצירת קשר וחשבון בנק, כדאי שיהיו זמינים במידע לעם, ואולי בהמשך נחשוב איך לממש את ההצגה שלהם באתר, אבל הם שדות חשובים ככל שאנחנו רוצים להנגיש את האפשרות להגיש בקשות מידע.

**Comment by OriHoch** [comment]
done and deployed

each entity's metadata is displayed in the group's about page
