### ISSUE TITLE
Format recognition when drag&drop

### ISSUE THREAD

**Issue by zomer-g** [OriHoch/data4dappl#77]
When using drag & drop system, the site doesn't auto recognize the format of the files and use just DATA tag for everything.

![image](https://user-images.githubusercontent.com/30901226/45253413-6b6f5400-b36f-11e8-8b49-5f595e439634.png)

**Comment by zomer-g** [comment]
![image](https://user-images.githubusercontent.com/30901226/45280629-d179e980-b4dd-11e8-8548-f97813390f37.png)

הוא ניסה להעלות, באחד הקבצים הגיע ל-100%, שם לוגו של שגיאה, ואז נכנס להקפאה של איזה 2 דקות. 

בסוף אחרי המתנה של כמה דקות, הוא העלה את כולם כביכול אבל כולם קיבלו תגית "שגיאה"

![image](https://user-images.githubusercontent.com/30901226/45280675-05eda580-b4de-11e8-8c4a-045a078169f1.png)

והמתנה נוספת וקפץ 502 על הכתובת
https://www.odata.org.il/file_uploader_ui/finish/tabar-jordanvalley

![image](https://user-images.githubusercontent.com/30901226/45280698-1867df00-b4de-11e8-8303-d37bc4913eaf.png)
 

בסופו של דבר, אחרי REFRESH של העמוד, הסתבר שעלו שני הקבצים הראשונים (מתוך 4 בלבד)

**Comment by zomer-g** [comment]
כרגע אחרי השלמה של ההעלאות, חלק בהעלאה רגילה וחלק בגרירה, הוא מתקשה לבצע שמירה של סדר הקבצים. 

![image](https://user-images.githubusercontent.com/30901226/45281323-27e82780-b4e0-11e8-92bb-fb4bd78aa5fa.png)


בסוף הסתדר, אבל משהו שם לא עובד חלק

**Comment by OriHoch** [comment]
sorry, you used it just while I was doing an upgrade.. try again, it should be OK now
