### ISSUE TITLE
number of clicks until reaching actual file should be reduced

### ISSUE THREAD

**Issue by OriHoch** [OriHoch/data4dappl#8]
<div dir=rtl>
לוקח כמה וכמה קליקים עד שמגיעים לקובץ עצמו באתר                        
המון קליקים
</div>

**Comment by zomer-g** [comment]
למעשה כרגע בדף פריט הכתובת היא
URL: www.odata.org.il/dataset/

שם יש קישור לפי שם הקובץ לדף
https://www.odata.org.il/dataset/<dataset>/resource/... (e.g.: e7de108a-7569-4f80-b5b8-9cc05a19f030)

ושם יש קשיור לקובץ עצמו
https://www.odata.org.il/dataset/... (e.g.:f0f3c2cc-05f7-4512-b7fc-db118f8703c8/resource/e7de108a-7569-4f80-b5b8-9cc05a19f030)/download/<filename>

רק צריך לשנות שהקישור בדף הפריט יהיה ישר לקובץ עצמו, בלי בכלל לאפשר גישה לעמוד האמצעי.

**Comment by OriHoch** [comment]
handled in #43
