### ISSUE TITLE
Simplifying the Add Item page

### ISSUE THREAD

**Issue by zomer-g** [OriHoch/data4dappl#82]
Enter most fields on the add Item page under the "Advanced Settings" button.

Create dataset page:
Tittle
URL
Description
Tags
Organization
Visibility

 all the others fields will be in "Advanced Settings"

**Comment by zomer-g** [comment]
בזמנו יצרת מנגנון כזה על מטאדאטה ברמת קובץ

לדוגמה
https://www.odata.org.il/dataset/3939daed-3e7a-442e-9c59-5157c9721fa4/resource/ed993168-bb10-4cc8-96ec-f19fbabff511

![image](https://user-images.githubusercontent.com/30901226/49318280-9d243100-f500-11e8-8f8a-7570d466d6ab.png)

**Comment by OriHoch** [comment]
deployed

**Comment by zomer-g** [comment]
https://github.com/OriHoch/data4dappl/issues/107
