### ISSUE TITLE
pipelines-admin-user documentation / log / monitoring / alerts

### ISSUE THREAD

**Issue by zomer-g** [OriHoch/data4dappl#84]
The data in the dashboard does not contain "pipelines-admin-user" activity, as the detailed screens at the document group level, organization or authority. If this involves insignificant development, it is better that this LOG also appear openly, for monitoring and control. 

Clarification: Full documentation appear in the user level, but it does not appear at the item level and in the main dashboard

https://www.odata.org.il/dashboard/

https://www.odata.org.il/user/pipelines-admin-user

כאן יש תיעוד מלא ברמת כל היוזרים מסודר

https://www.odata.org.il/revision

**Comment by OriHoch** [comment]
monitor and alert on the following conditions:
* errors in pipelines pod logs
* frequency of scheduled jobs

**Comment by OriHoch** [comment]
related issue: https://github.com/frictionlessdata/datapackage-pipelines/issues/153

**Comment by OriHoch** [comment]
use slack

**Comment by OriHoch** [comment]
fixed in [v0.1.0](https://github.com/OriHoch/data4dappl/releases) and deployed - sending notifications to hasadna slack channel odata-notifications
