### ISSUE TITLE
Facebook comments UI

### ISSUE THREAD

**Issue by zomer-g** [OriHoch/data4dappl#91]
Facebook's comments field has shrunk instead of being displayed across the entire page

![image](https://user-images.githubusercontent.com/30901226/46865356-f12a6780-ce25-11e8-8ea0-72a5b49f8cd3.png)

**Comment by OriHoch** [comment]
@zomer-g doesn't reproduce for me, maybe you have some privacy or ad blocking extensions?

screenshots from various browsers - 
[eb8a30d6866a780b295d0b0302a5ec6fd989a3c8.zip](https://github.com/OriHoch/data4dappl/files/2491440/eb8a30d6866a780b295d0b0302a5ec6fd989a3c8.zip)

**Comment by zomer-g** [comment]
now it's working well also for me
