### ISSUE TITLE
update odata extension arabic translations from transifex

### ISSUE THREAD

**Issue by OriHoch** [OriHoch/data4dappl#95]
it includes the strings for sending foi requests

**Comment by OriHoch** [comment]
fixed in 77da3796b53f7dff49b71470c40b9c33ad075d45

**Comment by zomer-g** [comment]
there is a small part that we need to complete

**Comment by OriHoch** [comment]
@zomer-g I don't see any changes in Transifex which are not in the site

could you send an example of a page which is missing translations?

**Comment by zomer-g** [comment]
i update the zoom-in and out translation to arabic

**Comment by OriHoch** [comment]
updated + deployed
