### ISSUE TITLE
automatically updated resources shouldn't appear in recent datasets feeds

### ISSUE THREAD

**Issue by OriHoch** [OriHoch/data4dappl#96]
they just appear at the top of the feed all the time - could either make them private, or hide them from the feeds

**Comment by zomer-g** [comment]
לא רואה סיבה שלא יהיו במצב פרטי וזהו. אין שם מידע שחשוב לנו להנגיש ומי שרוצה להתחבר לזה עם API ממילא יכול למצוא הכל בGIT.
