### ISSUE TITLE
entities import - should get from xml instead of json

### ISSUE THREAD

**Issue by OriHoch** [OriHoch/data4dappl#98]
fix for #71

**Comment by OriHoch** [comment]
list of updated / new groups from merging of xml and json entities

[foi_group_entities_2018-12-08.xlsx](https://github.com/OriHoch/data4dappl/files/2659801/foi_group_entities_2018-12-08.xlsx)

rows which have a value in `group_id` column - that group id will be updated (you can access the existing group at https://www.odata.org.il/group/about/GROUP_ID

I notice a lot of duplicates, here is an example which contains multiple problems:

[existing group](https://www.odata.org.il/group/about/foi-office-1433) - imported from json entities with entity_id `foi-office-1433` - same entity appears in new data under entity id `foi-office-6118` and duplicated again under entity id `foi-10-10277-bd31056e5a0f253c95ccb71fc03ffda9` from the XML

so there will be 3 groups for this entity after the update..

@zomer-g let's discuss how to handle this

**Comment by zomer-g** [comment]
I'll check again and talk with them about the duplicate issue, because last time I sent them an email about it and they fixed it.

**Comment by zomer-g** [comment]
* don't import new entities from the json
* only import new entities from the XML
* match entities from XML to existing CKAN groups by title
* exception for גבעולים
* export an excel containing:
  * all existing CKAN groups 
  * all new entities from XML
  * entities from XML which match existing group - will appear in 1 line
  * for each group include all data - both existing and new / updated
  * for updated groups - include group_id

**Comment by OriHoch** [comment]
@zomer-g check out this file with matching between xml and existing groups according to previous comment:
[match_foi_offices_xml_existing_entities.xlsx](https://github.com/OriHoch/data4dappl/files/3493665/match_foi_offices_xml_existing_entities.xlsx)
I think it's mostly good, there are some duplicates which needs to be handled manually, can discuss how to proceed

**Comment by zomer-g** [comment]
https://docs.google.com/spreadsheets/d/1dpyWq_3EC_ZImQT4Ef4EEYfInDkzCvkwmivpPZV16N0/edit?usp=sharing

**Comment by OriHoch** [comment]
update algorythm - based on following CSV produced from the spreadsheet in previous comment: 
[match_foi_offices_xml_existing_entities.txt](https://github.com/OriHoch/data4dappl/files/3519087/match_foi_offices_xml_existing_entities.txt)

* first iteration over all rows:
  * for each row which have non-empty `FOI match original_title`
    * update the group specified in the row's `group_id`
    * update/add data from the xml item matching the `FOI match original_title`
* second interation over all rows:
  * for each row which have empty `group_id`
    * for each row which `original_title` was not updated in first iteration:
      * add a new group from the xml item matching the `original_title`

**Comment by OriHoch** [comment]
following new groups are being added:

<pre dir=rtl>
אזור 2000 החברה לפתוח אזור (1992) בעמ
אזור חיפה (איכות סביבה)
איגוד השחייה בישראל
אנסמבל תאטרון הרצליה
בית בן גוריון
בית עריץ
בית שי עגנון
גבעון החדשה
גבעת חיים (מאוחד)
גוונים - החברה העירונית
גליל מזרחי
דיור מוגן ורווחה לקשיש -חברה לתועלת הציבור בעמ
דייר ראפאת
דריגאת
האגודה למפעלי תרבות ונוער - סינמטק תל אביב
האיגוד הירושלמי למאבק בסמים
האקדמיה הלאומית הישראלית למדעים
האקדמיה ללשון ערבית
ההתאחדות לכדורגל
הועדה המקומית לתכנון ובניה קריות
הועדה המרחבית לתכנון ובניה אבו בסמה
החברה הכלכלית אלפי מנשה
החברה הכלכלית לאריאל
החברה הכלכלית לפיתוח דרום השרון בעמ
החברה הכלכלית לפיתוח חולון
החברה הכלכלית לפיתוח יואב בעמ
החברה הכלכלית לפיתוח מעלה אדומים
החברה הכלכלית לפיתוח עמק חפר בעמ
החברה הכלכלית עירונית לפיתוח הוד השרון
החברה הכלכלית של טל עירון
החברה העירונית אריאל בעמ
החברה להגנת מצוקי חופי הים התיכון
החברה להשבת מי קולחין דרום השרון בעמ
החברה לטיפול במי קולחין קלנסואה לב השרון בעמ
החברה לפיתוח אתר הטבילה - בקעת הירדן בעמ
החברה לפיתוח חוף הכרמל בעמ
החברה לשירותי איכות הסביבה בעמ
הכרמלית חיפה בעמ
המועצה הישראלית לצרכנות
המועצה להשכלה גבוהה
המועצה לייצור ולשיווק אגוזי אדמה
המועצה לייצור ושיווק זיתים
המועצה לייצור צמחים ולשיווקם
המועצה למוצרי פרי הדר
המכון הגיאולוגי
המכון הרפואי לבטיחות בדרכים
המכון למורשת דוד בן גוריון
המכללה האקדמית אחוה
המכללה האקדמית להנדסה סמי שמעון
המרכז הארצי לפיתוח המקומות הקדושים
המרכז למורשת ששת הימים
העמותה לקליטת עליה בחיפה
העמותה לתרבות הפנאי חדרה
הרשות הלאומית לתרבות היידיש
הרשות הלאומית לתרבות הלאדינו
הרשות העירונית למאבק בהתמכרויות ובאלימות אשדוד
הרשות להגנת הצרכן ולסחר הוגן
הרשות לשירותים ציבוריים - חשמל
הרשות לשמירת הטבע והגנים הלאומיים
התאחדות הקליעה בישראל
התעשיה הצבאית לישראל בעמ (תעש)
ועדה תכנון מרחבית הגליל העליון
ועדה תכנון מרחבית ישובי הברון
ועדת תכנון מרחבית הראל
ועדת תכנון מרחבית הרצליה
חבר
חברה לפיתוח מצפה רמון בעמ
חברת דואר ישראל בעמ
חברת החשמל לישראל בעמ
חברת המושבים בדרום בעמ
חברת קולחי השרון בעמ
חברת רכבת ישראל מטענים בעמ
חלמיש - חברה עירונית לדיור וכו שכונות בתא יפו בעמ
חניתא
יודאיקה ביהודה
יזרעאלים
ייזום ראשון
יעדים החברה העירונית לפיתוח עסקי באר שבע
כוכב מיכאל
כפר הנוער מאיר שפיה
מבטחים
מבטיחים
מבני עציון
מגדל דוד המוזיאון לתולדות ירושלים
מוזיאון הצייר משה קסטל
מוזיאון חצר היישוב הישן
מוזיאון ישראל
מוזיאון לאמנות ישראלית רמת גן
מועצה אזורית חבל מודיעין
מועצה אזורית לב השרון
מועצה אזורית שדות דן
מועצה דתית אבן יהודה
מועצה דתית אור עקיבא
מועצה דתית אורנית
מועצה דתית אזור
מועצה דתית אליכין
מועצה דתית אלפי מנשה
מועצה דתית אשדוד
מועצה דתית אשקלון
מועצה דתית באר שבע
מועצה דתית בית דגן
מועצה דתית ביתר עילית
מועצה דתית בני ברק
מועצה דתית בנימינה
מועצה דתית גבעת זאב
מועצה דתית גבעת שמואל
מועצה דתית גדרה
מועצה דתית גני תקוה
מועצה דתית דימונה
מועצה דתית חולון
מועצה דתית חצור
מועצה דתית טבריה
מועצה דתית יהוד נוה מונסון
מועצה דתית ירושלים
מועצה דתית כפר יונה
מועצה דתית כפר סבא
מועצה דתית כפר תבור
מועצה דתית כרמיאל
מועצה דתית לכיש
מועצה דתית מגדל העמק
מועצה דתית מזכרת בתיה
מועצה דתית מטולה
מועצה דתית מיתר
מועצה דתית מנחמיה
מועצה דתית מעלות
מועצה דתית מרום הגליל
מועצה דתית נס ציונה
מועצה דתית סביון
מועצה דתית עכו
מועצה דתית עמנואל
מועצה דתית עמק המעיינות
מועצה דתית עפולה
מועצה דתית ערד
מועצה דתית עתלית
מועצה דתית פרדסיה
מועצה דתית צפת
מועצה דתית קצרין
מועצה דתית קרית אונו
מועצה דתית קרית ביאליק
מועצה דתית קרית טבעון
מועצה דתית קרית עקרון
מועצה דתית רחובות
מועצה דתית רכסים
מועצה דתית רמת ישי
מועצה דתית שדות נגב
מועצה דתית שומרון
מועצה דתית שלומי
מועצה דתית תל אביב-יפו
מועצה מקומית אבו גוש
מועצה מקומית אכסאל
מועצה מקומית אליכין
מועצה מקומית אלקנה
מועצה מקומית בוקעתא
מועצה מקומית ביר אל מכסור
מועצה מקומית בית דגן
מועצה מקומית בענה
מועצה מקומית ג'לג'וליה
מועצה מקומית ג'סר א-זרקא
מועצה מקומית דיר חנא
מועצה מקומית זמר
מועצה מקומית זרזיר
מועצה מקומית חורפיש
מועצה מקומית טובא זגריה
מועצה מקומית יבנאל
מועצה מקומית ירכא
מועצה מקומית כפר כנא
מועצה מקומית כפר מנדא
מועצה מקומית כפר קרע
מועצה מקומית לקיה
מועצה מקומית מג'דל שמס
מועצה מקומית מעיליא
מועצה מקומית משהד
מועצה מקומית סאג'ור
מועצה מקומית עילוט
מועצה מקומית עין מאהל
מועצה מקומית עמנואל
מועצה מקומית פרדסיה
מועצה מקומית קריית ארבע
מועצה מקומית קריית עקרון
מועצה מקומית ריינה
מועצה מקומית רכסים
מועצה מקומית שעב
מועצה מקומית תל מונד
מועצה מקומית תל שבע
מועצה מקומית-תעשייתית נאות חובב
מועצת ארגוני המתנדבים בירושלים
מועצת בתי העלמין היהודיים תל רגב
מזרח השרון
מי אונו
מי ברק תאגיד המים והביוב של בני ברק בעמ
מי הוד השרון בעמ
מי כרמל בעמ
מילב-מועדוני יום לגמלאים בחיפה
מינהל אזרחי אזור יהודה ושומרון (מנהאז יוש)
מכון היהלומים הישראלי
מכון ון ליר
מכון טכנולוגי חולון
מנהלת פארק תעשיות גליל תחתון
מעיינות העמקים בעמ
מעיינות זיו בעמ
מערך הסייבר הלאומי
מפעלי מעון
מרכז בריאות הנפש אברבנאל
מרכז רפואי שיבא
משרד החקלאות ופיתוח הכפר
מתאם פעולות הממשלה בשטחים (מתפש)
מתימופ - מרכז התעשיה הישראלית למחקר ופיתוח
מתן
מתש - מרכזי תעסוקה שיקומיים בעמ
מתת
מתתיהו
נ.ח.ל חדרה - נחלים חברה לתיירות בעמ
נ.ע.מ פארק תעשיות בעמ
נאות גולן
נאות הכיכר
נאות מורדכי
נאות סמדר
נאעורה
נבטים
נגבה
נגוהות
נהורה
נהלל
נוב
נוגה
נווה
נווה אור
נווה אטיב
נווה אילן
נווה איתן
נווה דניאל
נווה זוהר
נווה זיו
נווה חריף
נווה ים
נווה ימין
נווה ירק
נווה מבטח
נווה מיכאל
נווה שלום
נועם
נוף איילון
נופים
נופית
נופך
נוקדים
נורדייה
נורית
נחושה
נחל עוז
נחלה
נחליאל
נחלים
נחם
נחשולים
נחשון
נחשונים
נטועה
נטור
נטע
נטעים
נטף
ניין
נילי
ניסיון
ניצן
ניצן ב'
ניצנה (קהילת חינוך)
ניצני סיני
ניצני עוז
ניצנים
ניר אליהו
ניר בנים
ניר גלים
ניר דוד (תל עמל)
ניר חן
ניר יפה
ניר יצחק
ניר ישראל
ניר משה
ניר עוז
ניר עם
ניר עציון
ניר עקיבא
ניר צבי
נירים
נירית
נירן
נס הרים
נס עמים
נעורים
נעלה
נעמה
נען
נפת אשקלון (איכות הסביבה)
נצר חזני
נצר סרני
נתיב הגדוד
נתיב הלה
נתיב העשרה
נתיב השיירה
סאסא
סגולה
סואעד
סולם
סוסיה
סופה
סלמה
סלעית
סמר
סנסנה
סעד
סער
ספיר
סתרייה
עבדון
עברון
עגור
עד הלום
עדי
עדן החברה לפיתוח כלכלי בירושלים
עדנים
עוזה
עוזייר
עולש
עופר
עוצם
עזוז
עזר
עזרה ובצרון חברה לשיכון בעמ
עזריאל
עזריאלי המכללה האקדמית להנדסה ירושלים
עזריה
עזריקם
עטרת
עידן
עידן הנגב
עידן הנגב - איזור תעסוקה משותף בעמ
עיינות
עין איילה
עין אל-אסד'
עין אפק בעמ
עין גב
עין גדי
עין דור
עין הבשור
עין הוד
עין החורש
עין המפרץ
עין הנציב
עין העמק
עין השופט
עין השלושה
עין ורד
עין זיוון
עין חוד
עין חצבה
עין חרוד (האיחוד)
עין חרוד (מאוחד)
עין יהב
עין יעקב
עין כרם - ביס
עין כרמים - תאגיד מים וביוב בעמ
עין כרמל
עין נטפים - מפעלי מים וביוב אילת בעמ
עין נקובא
עין עירון
עין צורים
עין ראפה
עין שמר
עין שריד
עין תמר
עינת
עיר אובות
עיריית אלעד
עיריית אריאל
עיריית אשקלון
עיריית בית שאן
עיריית טייבה
עיריית טירה
עיריית טירת הכרמל
עיריית יבנה
עיריית יהוד - מונוסון
עיריית כפר יונה
עיריית כפר קאסם
עיריית כרמיאל
עיריית מגדל העמק
עיריית מעלה אדומים
עיריית נס ציונה
עיריית נצרת עילית
עיריית עראבה
עיריית קלנסווה
עיריית קריית אונו
עיריית קריית ים
עיריית קריית מלאכי
עלומים
עלי
עלי זהב
עלמה
עלמון
עמוקה
עמותה לחינוך ותרבות באזור באר טוביה
עמותה לפיקוח וניהול מרכז פיס סיעודי
עמותה לקידום הספורט ברמת הנגב
עמותה לקידום ספורט הפוטבול האמריקאי בישראל
עמותה לתיירות ונופש חיפה
עמותה עירונית לתרבות מודיעין מכבים רעות
עמותת אומנות ותרבות בגני-תקווה
עמותת בני הרצליה
עמותת התזמורת הסימפונית ראשון לציון
עמותת ספורט מיסודה של מ.א אזורית באר טוביה לתושביה
עמותת קהילת הדר חיפה
עמותת תמרית
עמינדב
עמיעד
עמיעוז
עמיקם
עמיר
עמית שהם
עמקה
ענב
ענבל חברה לבטוח בעמ
עפרה
עץ אפרים
עצמון שגב
עראמשה
ערב אל נעים
ערוגות
ערים חברה לפיתוח עירוני בעמ
עשות אשקלון תעשיות בעמ
עשרת
עתלית
עתניאל
פ.מ.ת - מבוא כרמל בעמ
פארן
פארק לאומי רמת גן
פארק תעשיות ספירים בעמ
פארק תעשיות רמת דלתון
פדואל
פדויים
פדיה
פורייה - כפר עבודה
פורייה - נווה עובד
פורייה עילית
פורת
פטיש
פי גלילות מסופים וצינורות נפט בעמ
פלג הגליל - החברה האזורית למים וביוב בעמ
פלגי מוצקין בעמ
פלך
פלמחים
פני חבר
פסגות
פעמי תשז
פצאל
פקיעין חדשה
פרוד
פרזון
פרזות חברה ממשלתית עירונית לשיכון ירושלים בעמ
פרי גן
פתחיה
צאלים
צביה
צבעון
צובה
צוחר
צופייה
צופים
צופית
צופר
צוקי ים
צוקים
צור הדסה
צור יצחק
צור משה
צור נתן
צוריאל
צורית
צחר פארק תעשיות הגליל
ציפורי
צלפון
צנדלה
צפרייה
צפרירים
צרופה
צרעה
ק.ה.ר קרן השתלמות לרוקחים בעמ
ק.ל.ע. - קרן השתלמות לעובדים הסוציאליים בעמ
קבוצת יבנה
קדמה
קדמת צבי
קדר
קדרון
קדרים
קו מוצרי דלק בעמ
קולחי גולן
קולחי גליל עליון בעמ
קולחי הגלבוע
קולחי משגב
קוממיות
קורנית
קטורה
קיסריה
קלחים
קליה
קלע
קנט - קרן לביטוח נזקי טבע בחקלאות בעמ
קסם
קציר
קצר א-סר
קריית הספורט והבילוי חיפה
קריית יערים (מוסד)
קריית נטפים
קריית ענבים
קריית שלמה
קרית חינוך גולן
קרן בני שמעון
קרנית - קרן לפיצוי נפגעי תאונות דרכים
קשת
ראס אל-עין
ראס עלי
ראש צורים
רבבה
רבדים
רביבים
רביד
רגבה
רגבים
רווחה
רוויה
רוח מדבר
רוחמה
רומאנה
רומת הייב
רועי
רותם
רחוב
רחלים
ריחאנייה
ריחן
רימונים
רימונים-חברה לפיתוח רמת השרון
רינתיה
רכס הכרמל
רם-און
רמות
רמות השבים
רמות מאיר
רמות מנשה
רמות נפתלי
רמת דוד
רמת הכובש
רמת השופט
רמת יוחנן
רמת מגשימים
רמת צבי
רמת רזיאל
רמת רחל
רנן
רעים
רקפת
רשות העתיקות
רשות נחל הירקון
רשות נחל קישון
רשות ניקוז ונחלים גליל מערבי
רשות ניקוז ונחלים ירדן דרומי
רשות ניקוז ונחלים ערבה
רשות ניקוז ונחלים קישון
רשות ניקוז ונחלים שרון
רשות ניקוז ים המלח
רשות ניקוז כנרת
רשות ניקוז כרמל
רשות ניקוז שורק - לכיש
רשות ניקוז שקמה בשור
רשפון
רשפים
רשת קהילה ופנאי חולון
רתמים
שאר ישוב
שבי ציון
שבי שומרון
שגיא 2000 (אזור תעשיה 99) בעמ
שדה אילן
שדה אליהו
שדה אליעזר
שדה בוקר
שדה דוד
שדה ורבורג
שדה יואב
שדה יעקב
שדה יצחק
שדה משה
שדה נחום
שדה נחמיה
שדה ניצן
שדה עוזיהו
שדה צבי
שדות ים
שדות מיכה
שדי אברהם
שדי חמד
שדי תרומות
שדמה
שדמות דבורה
שדמות מחולה
שואבה
שובה
שובל
שומרה
שומרון (איכות הסביבה)
שומרייה
שוקדה
שורקות
שורש
שורשים
שושנת העמק
שזור
שחמ - מקורות ביצוע
שחק פארק תעשיות צפון השומרון בעמ
שחר
שחרות
שיבולים
שיטים
שייח דנון
שילה
שילת
שכניה
שלווה
שלווה במדבר
שלוחות
שלומית
שמיר
שמעה
שמעונים נגב מזרחי
שמעונים נגב מערבי
שמרת
שמשית
שניר
שנקר - בית ספר גבוה להנדסה ולעיצוב
שעל
שעלבים
שער אפרים
שער הגולן
שער העמקים
שער מנשה
שערי תקווה
שפיים
שפיר
שפלת הגליל
שפר
שקד
שקמונה חברה ממשלתית עירונית לשקום הדיור בחיפה
שקף
שרונה
שרונים
שרונים - מפעלי מים וביוב בעמ
שריגים (לי-און)
שריד
שרשרת
שתולה
שתולים
תאגיד לחינוך שהם בעמ
תאגיד מי תקווה- גני תקווה
תאגיד מים וביוב העין השלישית רחובות
תאגיד פלגי שרון
תאשור
תדהר
תובל
תומר
תושייה
תיאטרון החאן הירושלמי
תיאטרון עירוני חיפה בעמ
תימורים
תירוש
תל יוסף
תל יצחק
תל עדשים
תל קציר
תל תאומים
תלם
תלמי אליהו
תלמי אלעזר
תלמי בילו
תלמי יוסף
תלמי יחיאל
תלמי יפה
תלמים
תמר - תאגיד מים אזורי
תמרת
תנובות
תעוז
תפרח
תקומה
תקוע
תרבין א-צאנע
תרום
תשתיות נפט ואנרגיה בעמ
תשתית - חברה לשירותי תחזוקה באשדוד בעמ
</pre>

**Comment by OriHoch** [comment]
done
